# Server related settings
address: 0.0.0.0
port: 1111
tls: false
cert: cert.pem
key: key.pem

# CORS configuration
cors:
  enabled: true
  credentials: true
  allowed_headers:
    - Depth
  allowed_hosts:
    - http://localhost:1111
  allowed_methods:
    - GET
  exposed_headers:
    - Content-Length
    - Content-Range

# 密码可以到https://bcrypt-generator.com/生成
# 然后password: "{bcrypt}加密密码"
users:
  - username: webdav
    password: 123456
    scopes:
      - root: E:/
        alias: pce
        rules:
          - path: /Downloads
            allow_w: true
      - root: F:/
        alias: pcf

